### ISSUE TITLE
Who explained the code on Thursday

### ISSUE THREAD

**Issue by Bryant-Xu** [dhuang12138/CS2820#10] opened 2016-12-06 20:16 UTC
Dear group number, we will have an presentation to show our group work on Thursday. i recommend our Master Di Huang to do that, because he is the person who knows most about this program.

**Comment by NickEBarnes** [comment] 2016-12-06 20:21
why was all my code completed deleted?

________________________________

**Comment by NickEBarnes** [comment] 2016-12-06 20:30
I'm just confused, I had committed in a while cause I was working through compile errors, then I go to pull and everything is gone? What happened? Everything I did is just gone?

**Comment by weigui** [comment] 2016-12-06 20:42
that's weird, you still have your codes right? pack them as a .zip file and upload it, See what we can do for you

**Comment by NickEBarnes** [comment] 2016-12-06 20:42
It looks like somebody went ahead and did their own belt and every other associated file

**Comment by di-huang** [comment] 2016-12-07 01:28
Your code is still at production_unitTesting file, I just made a new production because if not we will not have a runnable program right at the demo day.

**Comment by NickEBarnes** [comment] 2016-12-07 02:19
The problem is that Item and other classes have been changed and now are missing classes/constructors and everything else. It doesn't really matter though, I am now going to be on my own. I talked to Ted

________________________________

**Closed as completed** 2016-12-07 03:00 UTC
